name: Artifact

on: [pull]

env: 
  ARTIFACT_NAME: myartifact

jobs: 
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses:  action/checkout@v2
        run: 
      - name: Upload the artifact
        uses: action/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
    
    
